name: neso
description: "National Energy System Operator (NESO) app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.4.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter_launcher_icons: 0.14.1
  talker_flutter: 4.5.1
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^4.0.2

flutter_launcher_icons:
  image_path: "assets/neso_launcher.jpg"
  android: true
  ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/neso_launcher.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
